#include <stdio.h>   // Required for standard input/output (FILE, fopen, printf, fprintf, sscanf)
#include <stdlib.h>  // Required for general utilities (system function to run curl)
#include <string.h>  // Required for string operations (strstr to find text patterns)

// List of the 5 stock symbols we want to fetch from the Bombay Stock Exchange (BSE)
const char* companies[] = {
    "RELIANCE.BO",
    "TCS.BO",
    "INFY.BO",
    "HDFCBANK.BO",
    "ICICIBANK.BO"
};

int main() {
    // 1. Open the JavaScript file 'prices.js' in write mode ("w")
    // This file will be created or overwritten.
    FILE *jsFile = fopen("prices.js", "w");
    if (jsFile == NULL) {
        printf("Error: Could not open prices.js for writing.\n");
        return 1; // Exit the program with error code 1
    }

    // 2. Write the JavaScript variable structure to the file
    fprintf(jsFile, "// Auto-generated by C program. Do not modify.\n");
    fprintf(jsFile, "var livePrices = {\n");

    // 3. Loop through all 5 companies and fetch their real-time prices
    for (int i = 0; i < 5; i++) {
        char cmd[256];
        
        // Construct the curl command to download the JSON data from Yahoo Finance API.
        // We use a custom User-Agent (-A "Mozilla/5.0") so the server accepts our request.
        sprintf(cmd, "curl.exe -s -A \"Mozilla/5.0\" \"https://query1.finance.yahoo.com/v8/finance/chart/%s?interval=1d&range=1d\" > temp_stock.json", companies[i]);
        
        // Execute the curl command on the system
        system(cmd);

        // Open the temporary JSON file where the stock data was saved
        FILE *temp = fopen("temp_stock.json", "r");
        double price = -1.0; // Default price to -1.0 in case of failure

        if (temp != NULL) {
            char buffer[2048];
            // Read the contents of the temporary file into our buffer
            if (fgets(buffer, sizeof(buffer), temp) != NULL) {
                // Search for the "regularMarketPrice" tag inside the JSON response
                char *priceKey = strstr(buffer, "\"regularMarketPrice\":");
                if (priceKey != NULL) {
                    // Extract the numerical price value following the tag and store it in 'price'
                    sscanf(priceKey, "\"regularMarketPrice\":%lf", &price);
                }
            }
            // Close the temporary file
            fclose(temp);
            // Delete the temporary file from the disk to keep the folder clean
            remove("temp_stock.json");
        }

        // Write the company and its fetched price inside the JavaScript object.
        // If it is the last item (index 4), do not write a trailing comma.
        fprintf(jsFile, "    \"%s\": %.2f%s\n", companies[i], price, (i == 4) ? "" : ",");

        // Print the fetched stock price to the console so you can see it immediately
        if (price > 0) {
            printf("- %s: %.2f INR\n", companies[i], price);
        } else {
            printf("- %s: Failed to fetch price\n", companies[i]);
        }
    }

    // 4. Close the JavaScript object structure and close the file
    fprintf(jsFile, "};\n");
    fclose(jsFile);

    // Print a single success message and exit
    printf("Stock prices updated in 'prices.js' successfully!\n");
    return 0;
}
